version: 2.1
jobs:
  build:
    docker:
      - image: node:18.0.0
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@6.16.0 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: pnpm build

  lint:
    docker:
      - image: node:18.0.0
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@6.16.0 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: pnpm lint

  # test:
  #   docker:
  #     - image: node:18.0.0
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         name: Restore pnpm Package Cache
  #         keys:
  #           - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  #     - run:
  #         name: Install pnpm package manager
  #         command: |
  #           corepack enable
  #           corepack prepare pnpm@6.16.0 --activate
  #     - run:
  #         name: Install Dependencies
  #         command: |
  #           pnpm install
  #     - save_cache:
  #         name: Save pnpm Package Cache
  #         key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  #         paths:
  #           - node_modules
  #     - run:
  #         name: Test
  #         command: pnpm test

workflows:
  version: 2
  build-and-lint-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
          filters:
            branches:
              only: /.*/
      # - test:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: /.*/
