version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Build
          command: yarn build
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - build:
          filters:
            branches:
              ignore: master
            pull_requests:
              only: /^.*$/
