version: 2.1

jobs:
  run:
    executor: default
    steps:
      - run:
          name: client-test
          command: yarn test --cwd client
      - run:
          name: client-build
          command: yarn build --cwd client
      - run:
          name: server-build
          command: yarn build --cwd server

workflows:
  sample:
    jobs:
      - run
