version: 2.1

jobs:
  build:
    docker:
      - image: node:16.17.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build
          command: yarn build

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
