version: 2.1
jobs:
  common:
    docker:
      - image: node:16.17.0
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@^6 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

  build:
    steps:
      - attach_workspace:
          at: /common
      - run:
          name: Build
          command: |
            cd /common
            pnpm build

  lint:
    steps:
      - attach_workspace:
          at: /common
      - run:
          name: Lint
          command: |
            cd /common
            pnpm lint

workflows:
  version: 2
  build-and-lint:
    jobs:
      - common
      - build:
          requires:
            - common
      - lint:
          requires:
            - common
          filters:
            branches:
              only: /.*/
