# .circleci/config.yml
version: 2.1

import:
  - .circleci/common-config.yml

jobs:
  build:
    steps:
      - common_steps/common_steps
      - run:
          name: Build
          command: pnpm build

  lint:
    steps:
      - common_steps/common_steps
      - run:
          name: Lint
          command: pnpm lint

workflows:
  version: 2
  build-and-lint:
    jobs:
      - build
      - lint:
          requires:
            - build
          filters:
            branches:
              only: /.*/
