version: 2.1
orbs:
  node: circleci/node@4.7
workflows:
  sample:
    jobs:
      - node/test:
          name: client-test
          version: "16.10"
          pkg-manager: yarn
          steps:
            - run:
                name: client-test
                command: yarn test --cwd client
      - node/build:
          name: client-build
          version: "16.10"
          pkg-manager: yarn
          steps:
            - run:
                name: client-build
                command: yarn build --cwd client
      - node/build:
          name: server-build
          version: "16.10"
          pkg-manager: yarn
          steps:
            - run:
                name: server-build
                command: yarn build --cwd server
