version: 2.1

workflows:
  sample:
    jobs:
      - run:
          name: client-test
          command: yarn test --cwd client
      - run:
          name: client-build
          command: yarn build --cwd client
      - run:
          name: server-build
          command: yarn build --cwd server
