name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      HONEYPOT_SECRET: ${{ secrets.HONEYPOT_SECRET }}
      CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
      CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      FRONTEND_URL: "http://localhost:3000"
      CLOUDINARY_CLOUD_NAME: "bidhub"
      CLOUDINARY_LEGACY_URL: "https://api.cloudinary.com/v1_1/bidhub/image/upload"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      # - name: Start web server and save logs (with longer timeout)
      #   run: pnpm run dev > webserver.log 2>&1 &
      # - name: Wait for server to be ready
      #   run: |
      #     while ! nc -z localhost 3000; do
      #       sleep 1 # wait for 1 second before checking again
      #     done
      - name: Run Playwright tests
        run: pnpm run test:e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: webserver-logs
          path: webserver.log
          retention-days: 30
